### ISSUE TITLE
The method to save trained SEPP (or other models) and GUI issue

### ISSUE THREAD

**Issue by skepsun** [QuantCrimAtLeeds/PredictCode#4]
I have tried to use pickle to save the trained SEPP model. However, it failed with error that the local class cannot be pickled. I checked the code and found that functions such as make_kernel create local classes.
Also, I have tried GUI mode. When I clicked "run the current 'comparison' methods on this prediction run', the window just closed.
The log is as below:
`2017-07-17 00:34:36,244 ERROR open_cp.gui.tk.main_window_view - Exception: ['Traceback (most recent call last):\n', '  File "C:\\Users\\scx\\Anaconda3\\envs\\tensorflow\\lib\\tkinter\\__init__.py", line 1550, in __call__\n    return self.func(*args)\n', '  File "C:\\Users\\scx\\Anaconda3\\envs\\tensorflow\\lib\\tkinter\\__init__.py", line 596, in callit\n    func(*args)\n', '  File "F:\\Git\\PredictCode\\open_cp\\gui\\tk\\threads.py", line 42, in _query_task\n    task()\n', '  File "F:\\Git\\PredictCode\\open_cp\\gui\\tk\\threads.py", line 131, in on_gui_thread_task\n    at_finish(value)\n', '  File "F:\\Git\\PredictCode\\open_cp\\gui\\run_comparison.py", line 187, in _finished\n    self.controller.new_run_comparison_result(result)\n', '  File "F:\\Git\\PredictCode\\open_cp\\gui\\analysis.py", line 190, in new_run_comparison_result\n    self.view.update_run_analysis_results()\n', '  File "F:\\Git\\PredictCode\\open_cp\\gui\\tk\\analysis_view.py", line 386, in update_run_analysis_results\n    self._add_comparison_run_widgets(frame, row)\n', '  File "F:\\Git\\PredictCode\\open_cp\\gui\\tk\\analysis_view.py", line 421, in _add_comparison_run_widgets\n    self._add_comparison_row(comparison, row, subrow)\n', "TypeError: _add_comparison_row() missing 1 required positional argument: 'subrow'\n"]
Traceback (most recent call last):
  File "C:\Users\scx\Anaconda3\envs\tensorflow\lib\tkinter\__init__.py", line 1550, in __call__
    return self.func(*args)
  File "C:\Users\scx\Anaconda3\envs\tensorflow\lib\tkinter\__init__.py", line 596, in callit
    func(*args)
  File "F:\Git\PredictCode\open_cp\gui\tk\threads.py", line 42, in _query_task
    task()
  File "F:\Git\PredictCode\open_cp\gui\tk\threads.py", line 131, in on_gui_thread_task
    at_finish(value)
  File "F:\Git\PredictCode\open_cp\gui\run_comparison.py", line 187, in _finished
    self.controller.new_run_comparison_result(result)
  File "F:\Git\PredictCode\open_cp\gui\analysis.py", line 190, in new_run_comparison_result
    self.view.update_run_analysis_results()
  File "F:\Git\PredictCode\open_cp\gui\tk\analysis_view.py", line 386, in update_run_analysis_results
    self._add_comparison_run_widgets(frame, row)
  File "F:\Git\PredictCode\open_cp\gui\tk\analysis_view.py", line 421, in _add_comparison_run_widgets
    self._add_comparison_row(comparison, row, subrow)
TypeError: _add_comparison_row() missing 1 required positional argument: 'subrow'`

**Comment by MatthewDaws** [comment]
As for the GUI error: I think you're running old code!  Please do be aware that the GUI is very much a work in progress, and I tend to add things all the time, not all of which may be production quality.  I'll fix the pickle issue.

**Comment by MatthewDaws** [comment]
#38a9da4 fixes this.  Tested.

**Comment by skepsun** [comment]
Thanks for your response. I am sorry for that I did not realize that my local code was out of date!
