### ISSUE TITLE
Problem with logger

### ISSUE THREAD

**Issue by skepsun** [QuantCrimAtLeeds/PredictCode#5]
I find if I rerun my test code using open_cp logger : log_to_stdout, there will be two logger with same logs in the console.
Would it be possible to add some detection of whether there are existing loggers to avoid this problem?
In my local code, I just add `if (len(logger.handlers)==0):` in log_to_logger function.

**Comment by MatthewDaws** [comment]
Many thanks for the continued feedback!

I _think_ maybe this is again a case of out of date code.  The current code contains the method:

```
_current_handler = None

def _set_handler(handler):
    logger = _logging.getLogger("open_cp")
    global _current_handler
    if _current_handler is not None:
        logger.removeHandler(_current_handler)
    _current_handler = handler
    logger.addHandler(handler)
```

The purpose of this is to stop two loggers being attached at the time.  In a test script:

```
import open_cp.logger
import logging

open_cp.logger.log_to_stdout()
open_cp.logger.log_to_stdout()

logger = logging.getLogger("open_cp.matt")
logger.debug("A message")
```

I see only one message.

Can you verify that this is still a problem, and if so, post a minimal working example?

**Comment by skepsun** [comment]
Thanks for quick response.
I updated the code and ran the code you offered. If I run the code run for once, no repeated logs. However, if I _run it again_, then the logs repreat.
```
In [1]: runfile('F:/Git/PredictCode/tests/logger_test.py', wdir='F:/Git/PredictCode/tests')
2017-07-20 03:05:46,280 DEBUG open_cp.matt - A message

In [2]: runfile('F:/Git/PredictCode/tests/logger_test.py', wdir='F:/Git/PredictCode/tests')
Reloaded modules: open_cp, open_cp.logger, open_cp.data
2017-07-20 03:05:48,340 DEBUG open_cp.matt - A message
2017-07-20 03:05:48,340 DEBUG open_cp.matt - A message
```

**Comment by MatthewDaws** [comment]
Ah, right...  In a Jupyter notebook, I can recreate this using `importlib`:

```
import open_cp.logger
open_cp.logger.log_to_stdout()
logger = logging.getLogger("open_cp.matt")
logger.debug("A message")

import importlib
importlib.reload(open_cp.logger)

open_cp.logger.log_to_stdout()
logger.debug("A message")
```

Two messages!

I guess `importlib` resets the global variable(s) in `open_cp.logging` but not those in the `logging` module.

I've fixed this in a way whereby we can recognize an existing logger across a reload.  I want to leave the option of allowing the user to genuinely add another logger themselves.

See commit #26712d7
